# Generated by Django 5.2.5 on 2025-12-13 17:05

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('type', models.TextField(blank=True, choices=[('student', 'студент'), ('tutor', 'преподаватель')], null=True)),
                ('totp_key', models.CharField(blank=True, default=pyotp.random_hex, max_length=128, null=True)),
                ('can_see_test_questions', models.BooleanField(blank=True, db_default=False, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_students', 'Может создавать студентов'), ('can_see_test_questions', 'Может видеть вопросы тестов'), ('can_see_all_students', 'Может видеть всех студентов'), ('can_see_all_results', 'Может видеть все результаты')],
            },
        ),
    ]
