# Generated by Django 5.2.5 on 2025-12-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_see_all_students', 'Может видеть всех студентов'), ('can_create_students', 'Может создавать студентов'), ('can_update_students', 'Может редактировать студентов'), ('can_delete_students', 'Может удалять студентов'), ('can_see_himself', 'Может видеть только себя'), ('can_see_test_questions', 'Может видеть вопросы тестов'), ('can_create_test_questions', 'Может создавать вопросы тестов'), ('can_update_test_questions', 'Может редактировать вопросы тестов'), ('can_delete_test_questions', 'Может удалять вопросы тестов'), ('can_see_test_question_variants', 'Может видеть варианты вопросов'), ('can_create_test_question_variants', 'Может создавать варианты вопросов'), ('can_update_test_question_variants', 'Может редактировать варианты вопросов'), ('can_delete_test_question_variants', 'Может удалять варианты вопросов'), ('can_see_all_results', 'Может видеть все результаты'), ('can_see_own_results', 'Может видеть только свои результаты'), ('can_see_all_tutors', 'Может видеть всех преподавателей'), ('can_see_his_tutor', 'Может видеть своего преподавателя'), ('can_create_tutors', 'Может создавать преподавателей'), ('can_update_tutors', 'Может редактировать преподавателей'), ('can_delete_tutors', 'Может удалять преподавателей')]},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_see_test_questions',
        ),
    ]
