# Generated by Django 5.2.5 on 2025-09-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Правильный ответ')),
                ('variants', models.TextField(verbose_name='Варианты')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(verbose_name='Слово')),
                ('translation', models.TextField(verbose_name='Перевод')),
                ('picture', models.TextField(verbose_name='Картинка')),
                ('topic', models.TextField(verbose_name='Тема')),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.TextField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.TextField(verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='student',
            name='progress',
            field=models.IntegerField(verbose_name='Прогресс'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.student', verbose_name='Ученик')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test', verbose_name='Тест')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='words',
            field=models.ManyToManyField(to='english.word', verbose_name='Слова для теста'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltopic', models.TextField(verbose_name='Тема урока')),
                ('ltest', models.DateField(verbose_name='Дата')),
                ('homework', models.TextField(verbose_name='Домашнее задание')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='english.test', verbose_name='Тест урока')),
                ('words', models.ManyToManyField(to='english.word', verbose_name='Список слов')),
            ],
        ),
    ]
