# Generated by Django 5.2.5 on 2025-09-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_test_word_alter_student_options_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='test',
            name='words',
        ),
    ]
