# Generated by Django 5.2.5 on 2025-10-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_student_options_remove_test_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='variants',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='basetest', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=50, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('variants', models.TextField(verbose_name='Варианты')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_corect', models.BooleanField()),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.testquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
