# Generated by Django 5.2.5 on 2025-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_remove_test_answer_remove_test_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='students', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='picture',
            field=models.ImageField(null=True, upload_to='testQuestions', verbose_name='Изображение'),
        ),
    ]
