# Generated by Django 5.2.5 on 2025-11-07 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_student_picture_testquestion_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фото студента'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение вопроса'),
        ),
    ]
