# Generated by Django 5.2.5 on 2025-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_student_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, to='english.test', verbose_name='Назначенные тесты'),
        ),
    ]
