# Generated by Django 5.2.5 on 2025-12-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_student_assigned_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='variants',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='english.test'),
        ),
    ]
