# Generated by Django 5.2.5 on 2025-12-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_remove_testquestion_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testquestionvariant',
            old_name='is_corect',
            new_name='is_correct',
        ),
    ]
