# Generated by Django 5.2.5 on 2025-12-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0012_rename_is_corect_testquestionvariant_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionvariant',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='english.testquestion'),
        ),
    ]
